apiVersion: autoscaling/v1 
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
spec: 
   scaleTargetRef:
     kind: Deployment
     name: php-apache
     apiVersion: apps/v1
   minReplicas: 1
   maxReplicas: 10
   targetCPUUtilizationPercentage: 40
   