apiVersion: v1
kind: Pod 
metadata:
  name: init-pod
  labels:
    app: init-pod
spec: 
  containers:
    - name: nginx
      image: nginx:latest
  initContainers:
    - name: svc-check
      image: busybox:1.27
      command: ['sh', '-c', 'until nslookup shipping-svc; do echo waiting for shipping-svc; sleep 2; done']