kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata: 
  name: aws-standart
provisioner: kubernetes.io/aws-ebs 
volumeBindingMode: WaitForFirstConsumer
parameters: 
  type: gp2
  fstType: ext4
  